# Generated by Django 4.2.5 on 2023-10-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='name')),
                ('number_of_inventory', models.PositiveIntegerField(default=0, verbose_name='number of inventory')),
                ('price', models.FloatField(verbose_name='price')),
                ('first_record_date', models.DateTimeField(auto_now_add=True, verbose_name='first record date')),
                ('last_charge_date', models.DateTimeField(auto_now_add=True, verbose_name='last charge date')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
        ),
    ]
